FROM eclipse-temurin:17-jre-focal

EXPOSE 8080

ARG DBMS_PROD
ENV DBMS ${DBMS_PROD}
ARG DB_HOST_PROD
ENV DB_HOST ${DB_HOST_PROD}
ARG DB_PORT_PROD
ENV DB_PORT ${DB_PORT_PROD}
ARG DB_NAME_PROD
ENV DB_NAME ${DB_NAME_PROD}
ARG DB_PASSWORD_PROD
ENV DB_PASSWORD ${DB_PASSWORD_PROD}
ARG DB_USERNAME_PROD
ENV DB_USERNAME ${DB_USERNAME_PROD}}
ARG SHOW_SQL_PROD
ENV SHOW_SQL ${SHOW_SQL_PROD}
ARG DDL_AUTO_MODE_PROD
ENV DDL_AUTO_MODE ${DDL_AUTO_MODE_PROD}
ARG DB_POOL_PROD
ENV DB_POOL ${DB_POOL_PROD}
ARG AUTHORITY_SERVICE_HOST_PROD
ENV AUTHORITY_SERVICE_HOST ${AUTHORITY_SERVICE_HOST}
ARG APPLICATION_SERVICE_HOST_PROD
ENV APPLICATION_SERVICE_HOST ${APPLICATION_SERVICE_HOST}
ARG JWT_SECRET_KEY_PROD
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY_PROD}
ARG JWT_ACCESS_TOKEN_EXP_AS_HOUR_PROD
ENV JWT_ACCESS_TOKEN_EXP_AS_HOUR ${JWT_ACCESS_TOKEN_EXP_AS_HOUR_PROD}
ARG JWT_REFRESH_TOKEN_EXP_AS_HOUR_PROD
ENV JWT_REFRESH_TOKEN_EXP_AS_HOUR ${JWT_REFRESH_TOKEN_EXP_AS_HOUR_PROD}

ADD user-infrastructure/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]