FROM eclipse-temurin:17-jre-focal

EXPOSE 8080

ARG DBMS
ENV DBMS ${DBMS}
ARG DB_HOST
ENV DB_HOST ${DB_HOST}
ARG DB_PORT
ENV DB_PORT ${DB_PORT}
ARG DB_NAME
ENV DB_NAME ${DB_NAME}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}
ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}
ARG SHOW_SQL
ENV SHOW_SQL ${SHOW_SQL}
ARG DDL_AUTO_MODE
ENV DDL_AUTO_MODE ${DDL_AUTO_MODE}
ARG DB_POOL
ENV DB_POOL ${DB_POOL}
ARG AUTHORITY_SERVICE_HOST
ENV AUTHORITY_SERVICE_HOST ${AUTHORITY_SERVICE_HOST}
ARG APPLICATION_SERVICE_HOST
ENV APPLICATION_SERVICE_HOST ${APPLICATION_SERVICE_HOST}
ARG JWT_SECRET_KEY
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}
ARG JWT_ACCESS_TOKEN_EXP_AS_HOUR
ENV JWT_ACCESS_TOKEN_EXP_AS_HOUR ${JWT_ACCESS_TOKEN_EXP_AS_HOUR}
ARG JWT_REFRESH_TOKEN_EXP_AS_HOUR
ENV JWT_REFRESH_TOKEN_EXP_AS_HOUR ${JWT_REFRESH_TOKEN_EXP_AS_HOUR}

ADD user-infrastructure/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]