object DependencyVersions {
    const val KTLINT_VERSION = "0.44.0"
    const val SPRING_CLOUD_VERSION = "2021.0.1"
    const val AWS_MESSAGING_VERSION = "2.2.6.RELEASE"
    const val REACTIVE_MYSQL_VERSION = "4.2.5"
    const val EMBEDDED_MYSQL_VERSION = "4.6.2"
    const val HIBERNATE_REACTIVE_VERSION = "1.1.3.Final"
    const val MUTINY_VERSION = "1.4.0"
    const val JDSL_VERSION = "2.0.1.RELEASE"
    const val COROUTINE_VERSION = "1.6.1"
    const val RABBIT_VERSION = "2.4.3"
    const val MAPSTRUCT_VERSION = "1.4.2.Final"
    const val MOCKK_VERSION = "1.12.3"
    const val SPRING_MOCKK_VERSION = "3.1.1"
}
