spring:
  main:
    web-application-type: reactive
  datasource:
    dbms: ${DBMS}
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    show-sql: ${SHOW_SQL}
    format-sql: false
    highlight-sql: false
    ddl-auto: ${DDL_AUTO_MODE}
    pool-size: ${DB_POOL}
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  application:
    name: user-service-v1
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: ${ZIPKIN_URL}
    sender:
      type: rabbit
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized

service:
  authority:
    host: ${AUTHORITY_SERVICE_HOST}
    get-authority-endpoint: ${GET_AUTHORITY_ENDPOINT}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    show-sql: true
    format-sql: true
    highlight-sql: true