spring:
  main:
    web-application-type: reactive
  kafka:
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      bootstrap-servers: ${KAFKA_URLS}
      properties:
        spring.json.add.type.header: false
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 2
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_URLS}
    bootstrap-servers: ${KAFKA_URLS}
  datasource:
    dbms: ${DBMS}
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    show-sql: ${SHOW_SQL}
    format-sql: false
    highlight-sql: false
    ddl-auto: ${DDL_AUTO_MODE}
    pool-size: ${DB_POOL}
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  application:
    name: user-service-v1
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: ${ZIPKIN_URL}
    sender:
      type: rabbit
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

server:
  port: ${SERVER_PORT}
  shutdown: graceful

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    # when we run spring cloud on EC2, it starts CloudFormation setting. If we don't, our application doesn't start
    # So I turn of this setting
    stack:
      auto: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    show-sql: true
    format-sql: true
    highlight-sql: true