spring:
  profiles:
    active: ${PROFILE}
  main:
    web-application-type: reactive
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  application:
    name: v1-user-service
  config:
    import: ${CLOUD_CONFIG_IMPORT_URL:optional:configserver:https://api.xquare.app/cloud-config/}
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}

server:
  shutdown: graceful
  scheme: ${SCHEME}
  host: ${HOST}
  port: ${PORT}
  database: ${DB_NAME}
  username: ${USERNAME}
  password: ${PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized

excel:
  url: ${EXCEL_URL}